### ISSUE TITLE
img broken

### ISSUE THREAD

**Issue by mosiahrs** [birobirobiro/pokedex#1]
## Erro ao carregar imagem

![image](https://user-images.githubusercontent.com/100864562/185925184-30526210-c6a3-47dd-804b-35a79b673825.png)

As sprites selecionadas na pokeApi, só vão até o nº 649. A partir da 650º não carregam, provavelmente não tem disponível no formato selecionado. 
Sugiro que crie uma regra para que a partir de 650 utilize outro formato de Sprite.

**Comment by birobirobiro** [comment]
Obrigado por avisar, acabei de mandar uma [PR](https://github.com/birobirobiro/pokedex/pull/2) que corrige todas as gerações dos Pokémons.
